# MongoDB Configuration
mongodb:
  host: localhost
  port: 27017
  database: prismamc_trade
  collection: trades
  username: ""
  password: ""
  auth-database: admin
  connection-uri: "" # Optional: if provided, will override host/port settings

# Command Settings
commands:
  trade:
    cooldown: 5 # Cooldown in seconds between trade commands

# Player Settings
player:
  default-language: "en" # Default language for new players

